data_path: "/content/drive/Shareddrives/recommendation-systems/Research Project/Code/data/"
index_dir: "/content/drive/Shareddrives/recommendation-systems/Research Project/Code/data/"
lr: 0.001
epochs: 100
batch_size: 128
cuda: false
log_interval: 200
checkpoint: "/content/"
outf: "generated.txt"
endure_times: 5
words: 20
dataset: "TripAdvisor"
fold: 1
